### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jfrux** [TheRealAgentK/facebook-cf-sdk#21]
Any tips for best overall performance using the SDK? Your most advisable best practice?
Does it not make sense to use natural http page changes attaching the signed_request to each link?

**Comment by benorama** [comment]
It depends if you use the SDK on apps on Facebook or on your website.
For example, on our apps on Facebook, we use Ajax reloading techniques to improve user experience and in that case, we pass the signed_request through each links / reload so that we keep all the info around the app.
This was required  with the previous SDK, with the new one, user info are stored in the session scope so it is not really required anymore (except that you will loose the info the current page and if the user has liked the page).

On website, the signed request is stored in a "fbsr_YOUR_APP_ID" cookie and send to your server on each request. So you don't need to attach the signed_request to each link.

The best tips performance is to reduce as much as possible HTTP calls to the Graph API. 
Each request takes around 1s, so cache as much as possible on your side!

**Comment by jfrux** [comment]
Basically my app is a hybrid and has page tabs too.
How can I be sure how many times graph is being called versus being cached in session?
I'm thinking it's not caching because it's taking too long per page request.

EEK!

I deeply appreciate your help in this, you've been a huge help.

Thanks!

**Comment by benorama** [comment]
Are you using beta-4 of the SDK (latest version)?
There is a bug corrected concerning unnecessary calls.

On a website with Facebook Connect, you should have only one call to the OAuth API to get the user access token from the authorization code returned from FB.login (in stored inside the fbsr_ signed request cookie). After login, user id and access token are stored in the session scope.

On an apps running in Facebook, you should have one call to the OAuth API when the user authorize the app to get the user access token from the authorization code.
Once the app is authorized, when the user come back to your app, you should not have any Graph API calls because the access token is already inside the signed request (sent to the iframe page).

You can check graph API calls by putting a writeLog inside the callApi method inside FacebookBase.cfc.

**Comment by jfrux** [comment]
This sounds great, how do I know which version that I originally downloaded?
I just downloaded these files maybe 2 weeks ago...?

**Comment by benorama** [comment]
So you are probably using beta-2.
You might want to download the latest version with the latest bug fixes.

**Comment by jfrux** [comment]
Awesome, will do! This is great - thank you for your time... is there a place to financially support your efforts?

**Comment by benorama** [comment]
You're welcome. :)

If you want to help us, do not hesitate to recommend our "fantastic" Facebook Page Management platform : http://agorapulse.com

**Comment by jfrux** [comment]
so do I need to manually determine if I should create a "new graphapi" variable based on the results of the signed_request? or does the FacebookApp instance know?

Because currently no matter what I do I'm getting at least 3 graphapi requests logged each request.

**Comment by jfrux** [comment]
nevermind I think I get it now, sorry!

**Comment by jfrux** [comment]
Nvm, I'm still confused...
Let's say I have a user table in my database and I store the Fb_id of the user...
Where / how would you handle this?

The user arrives on a random page at any given time...
The FB component dissects the signed request and then i use graphapi to check the user and if things checkout I manually create session variables that hold my local db info about the user such as session.userid or what?

Then with JS SDK I could send a call to a logout script on authStatusChange or whatever?

I'm really confused on this unfortunately... :-\

**Comment by benorama** [comment]
You should not have to manually create session variables with the userId and accessToken, the SDK does it for you. You can cfdump session scope to check them.

If you want to logout the user from your app AND from Facebook.com, you must use the JS SDK FB.logout() method.

If you want to logout the user only from your app, you can use CF Facebook Graph API invalidateUser() method (it will clear the session and the cookie for you).
