### ISSUE TITLE
Mixed-up sessions

### ISSUE THREAD

**Issue by VosAndHowden** [TheRealAgentK/facebook-cf-sdk#28]
We're getting limited reports of users logging in via FB to our app, but they get connected to someone else's session.  We've been unable to reproduce.

**Comment by benorama** [comment]
We are using the SDK on production and we have never heard of issues like that. 
This probably not linked to the SDK since sessions are handled by ColdFusion.
Are you using standard J2EE sessions in ColdFusion?

**Comment by VosAndHowden** [comment]
We haven't encountered any other issues on the same serve with shared sessions like this so it's not a CF/server config issue.

Why was the SDK changed to use sessions to begin with?  It was with the release that introduce the use of sessions that this issue cropped up.

**Comment by benorama** [comment]
WIth OAuth1.0 (previous release), Facebook was directly sending the user access token in the signed request session cookie.
With OAuth2.0, Facebook does not return directly user access_token. It returns an authorization "code" parameter that your server must use to get the user access token : 
https://developers.facebook.com/docs/authentication/

The user access token is stored/cached in the session scope for performance reason, otherwise you would have a request to Facebook for each page request (at least one second penalty....).

The logic we have implemented is exactly the same as the one in official PHP SDK.

Can you easily reproduce the issue? If yes, can you check the values of session and cookie scopes?
