### ISSUE TITLE
Everything still working with recent FB changes?

### ISSUE THREAD

**Issue by jfrux** [TheRealAgentK/facebook-cf-sdk#32]
I can't seem to get your example site to not throw an error on the FB side when I click "Login with Facebook"

Also, getting an oAuth error when coming back to the redirect_uri I provided.

:-\

I'm probably just being ignorant but if you can confirm that would be helpful!

**Comment by jfrux** [comment]
Apparently I'm being dumb, I was logged in a test user that's why the example page didn't work.
HOWEVER, I'm still getting an error on my app...
OAuthException - Error validating verification code.

It's a local dev environment, could that be it?
Also, I'm doing a cflocation to go to the authorization site, it's accepting my authorization when I click Allow it redirects back and bombs...

I can't seem to figure it out... lol

**Comment by jfrux** [comment]
Here is the url's format when it returns back:
http://devsite/oauth/facebookverify/?state=98F390692791F2DD777A55596A69A46E&code=AQCVsG07_9man4SP4-lBrHyTC0CpzGdzCvjR74RRVwxleQCiRtLEgP89aeqGNjs-NIQVfJLiE5N0HEqkSHIAmQakLqH1JQ6ptsrvC6MLEc8PwlX_ev0AW1TCHNnBZwQEUVyMSuZqTb5AbivId8GDD-hgB6ghUwD73CQHqWGJ_cMxw3Jd1GRoqR30LwkijJRjCQM#_=_

**Comment by benorama** [comment]
Do you still face thoses issues?
The SDK should work as expected even with recent FB changes.

**Comment by TheRealAgentK** [comment]
Hmm, I seem to have exactly the same issue. Same URL structure, when I try to run facebookApp.getUserId() (any function on it really) it returns 

OAuthException - Error validating verification code. [code=100]

**Comment by TheRealAgentK** [comment]
And this seems to be the issue:

I was running getUserID() - my oAuth call returned a code via the URL and I actually redirect to a _different_ URL than the one the authentication was started from. The library seems to run through:

FacebookApp.cfc - line 274
accessToken = getAccessTokenFromCode(code);

line 439:
if (!structKeyExists(arguments, "redirectUri")) {
   arguments.redirectUri = getCurrentUrl();
}

getCurrentURL returns a variable of the form:

http://www.blabla.com/index.cfm/en/whatever/doSomeFBAuth

However - the variable I tell FB to redirect TO was http://www.blabla.com/en/whatever/doSomeFBAuth because there's a rewrite rule in place that the FB CF SDK obviously doesn't know anything about it.

So from FB's point of view, I've juggled 2 different URLs for getting the code and getting the token and that's why it failed the oAuth.

@JoshuaIRL - I wonder if you're running into a similar issue. Fix would most likely be to just pass in the full URL including the index.cfm to the first oAuth call as redirectURL.

**Comment by benorama** [comment]
Have you tried to pass the correct redirect_uri as a parameter to getLoginUrl() ?

Otherwise, you might try to use the Facebook JS SDK to handle the connection (with the login-link custom tag).
